name: halo
description: Personal flutter all-in-one package.
version: 0.0.21
homepage: https://github.com/HaloWang/halo_flutter

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=1.17.0'

dependencies:
  collection: ^1.18.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
